[package]
name = "rust_arcade_display"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.7.0"
rust_arcade = { path = "../rust_arcade" }
particles = { path = "../particles" }